# Generated by Django 5.0.10 on 2024-12-16 10:41

import acctmarket.utils.models
import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.CharField(default=acctmarket.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the SMS campaign for identification.', max_length=255)),
                ('message', models.TextField(help_text='The SMS message content to be sent to recipients.')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Draft', 'Draft'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled'), ('No recipient', 'No recipient')], default='Draft', help_text='The current status of the SMS campaign.(leave as draft system will update authomatically)', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Time to send the campaign.', null=True)),
            ],
            options={
                'verbose_name': 'SMS Campaign',
                'verbose_name_plural': 'SMS Campaigns',
                'ordering': ['-created_at', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=acctmarket.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('WALLET_DEBIT', 'WALLET_DEBIT'), ('WALLET_CREDIT', 'WALLET_CREDIT'), ('PAYMENT_fAILED', 'PAYMENT_fAILED'), ('PAYMENT_SUCCESS', 'PAYMENT_SUCCESS')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.CharField(default=acctmarket.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total_referred_spend', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('first_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('referred_user_signup_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('wallet_funded', models.BooleanField(blank=True, default=False, null=True)),
                ('first_purchase_done', models.BooleanField(default=False)),
                ('referred_user', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refered_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=acctmarket.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.CharField(default=acctmarket.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='DEBIT', max_length=6)),
                ('wallet', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='refer.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
