volumes:
  acctmarket_local_postgres_data: {}
  acctmarket_local_postgres_data_backups: {}
  acctmarket_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: acctmarket_local_django
    container_name: acctmarket_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: acctmarket_production_postgres
    container_name: acctmarket_local_postgres
    volumes:
      - acctmarket_local_postgres_data:/var/lib/postgresql/data
      - acctmarket_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: acctmarket_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: acctmarket_local_redis

    volumes:
      - acctmarket_local_redis_data:/data


  # celeryworker:
  #   <<: *django
  #   image: acctmarket_local_celeryworker
  #   container_name: acctmarket_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: acctmarket_local_celerybeat
  #   container_name: acctmarket_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: acctmarket_local_flower
  #   container_name: acctmarket_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
