# Generated by Django 5.0.9 on 2024-12-04 09:10

import auto_prefetch
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('ecommerce', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='featured_category',
            field=auto_prefetch.ForeignKey(blank=True, help_text='choose products by category only', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category', verbose_name='Banner category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='featured_product',
            field=auto_prefetch.ForeignKey(blank=True, help_text='choose products by a particular product only', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Banner product'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='sub_category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Blog Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ecommerce.CharUUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Post'),
        ),
    ]
